/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Author = IDL.Variant({
  'ai' : IDL.Null,
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const GeminiMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : Author,
});
export const UserProfile = IDL.Record({
  'focusArea' : IDL.Text,
  'ageGroup' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Goal = IDL.Record({
  'completed' : IDL.Bool,
  'description' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const MoodEntry = IDL.Record({ 'mood' : IDL.Text, 'note' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGoal' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMoodEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'aiChat' : IDL.Func(
      [IDL.Vec(GeminiMessage), UserProfile, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyMotivation' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getGoals' : IDL.Func([IDL.Principal], [IDL.Vec(Goal)], ['query']),
  'getJournalEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'getMoodLogs' : IDL.Func([IDL.Principal], [IDL.Vec(MoodEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleGoalCompletion' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Author = IDL.Variant({
    'ai' : IDL.Null,
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const GeminiMessage = IDL.Record({ 'content' : IDL.Text, 'role' : Author });
  const UserProfile = IDL.Record({
    'focusArea' : IDL.Text,
    'ageGroup' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Goal = IDL.Record({ 'completed' : IDL.Bool, 'description' : IDL.Text });
  const JournalEntry = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const MoodEntry = IDL.Record({ 'mood' : IDL.Text, 'note' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGoal' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMoodEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'aiChat' : IDL.Func(
        [IDL.Vec(GeminiMessage), UserProfile, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyMotivation' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getGoals' : IDL.Func([IDL.Principal], [IDL.Vec(Goal)], ['query']),
    'getJournalEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getMoodLogs' : IDL.Func([IDL.Principal], [IDL.Vec(MoodEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleGoalCompletion' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };